import csv
import random
from pathlib import Path

BASE = Path(__file__).parent
OUT = BASE / "game_library.csv"

# --- Базовые списки ---

GENRES = [
    ["Shooter", "Action"],
    ["RPG", "Action"],
    ["Strategy", "RTS"],
    ["Strategy", "Turn-Based"],
    ["Survival", "Sandbox"],
    ["Survival", "Horror"],
    ["Simulation", "Sandbox"],
    ["Action", "Adventure"],
    ["Shooter", "RPG"],
    ["Action", "Platformer"],
    ["Puzzle", "Adventure"],
    ["Racing"],
    ["Sports"],
    ["MOBA", "Strategy"],
    ["Battle Royale", "Shooter"],
    ["Tactical", "Shooter"],
    ["Party", "Action"],
    ["Casual", "Party"],
    ["4X", "Strategy"],
    ["Grand Strategy", "Strategy"],
    ["Simulation"],
    ["Sandbox"],
]

PLATFORMS_POOL = [
    "PC",
    "PC;PS5",
    "PC;Xbox",
    "PC;PS4;Xbox",
    "PC;PS5;Xbox",
    "PC;PS4;Xbox;Switch",
    "PC;PS5;Xbox;Switch",
    "PS5;Xbox",
    "Xbox",
    "PC;Switch",
]

FREE2PLAY_POSSIBILITIES = ["Yes", "No", "No", "No", "No"]  # ~20% free

# --- Списки названий (примерно 250–300 шаблонов) ---

FRANCHISES = [
    "Halo",
    "Call of Duty",
    "Battlefield",
    "Destiny",
    "The Division",
    "Borderlands",
    "Warframe",
    "Monster Hunter",
    "Dark Souls",
    "Elden Ring",
    "Fallout",
    "The Elder Scrolls",
    "Gears of War",
    "Forza",
    "FIFA",
    "NBA 2K",
    "Madden NFL",
    "Rocket League",
    "Overwatch",
    "Apex Legends",
    "Rainbow Six",
    "Counter-Strike",
    "Team Fortress",
    "Left 4 Dead",
    "Back 4 Blood",
    "Dying Light",
    "Dead Island",
    "Far Cry",
    "Assassin's Creed",
    "Grand Theft Auto",
    "Red Dead",
    "Saints Row",
    "Payday",
    "Killing Floor",
    "Warhammer",
    "Total War",
    "Age of Empires",
    "Company of Heroes",
    "Civilization",
    "Anno",
    "Cities",
    "SimCity",
    "Frostpunk",
    "XCOM",
    "Phoenix Point",
    "Stellaris",
    "Hearts of Iron",
    "Crusader Kings",
    "Europa Universalis",
    "Factorio",
    "Satisfactory",
    "RimWorld",
    "Oxygen Not Included",
    "Two Point",
    "Planet Coaster",
    "Jurassic World Evolution",
    "Kerbal Space Program",
    "Subnautica",
    "The Forest",
    "Green Hell",
    "Raft",
    "Valheim",
    "Terraria",
    "Minecraft",
    "Stardew Valley",
    "Don't Starve",
    "Project Zomboid",
    "7 Days to Die",
    "Rust",
    "No Man's Sky",
    "The Long Dark",
    "Deep Rock Galactic",
    "Remnant",
    "Outriders",
    "Tiny Tina",
    "Cuphead",
    "Hollow Knight",
    "Celeste",
    "Ori",
    "Metroid",
    "Castlevania",
    "Trine",
    "Portal",
    "Half-Life",
    "BioShock",
    "Dishonored",
    "Prey",
    "Wolfenstein",
    "Doom",
    "Quake",
    "Heretic",
    "Hexen",
    "Blood",
    "Redneck Rampage",
    "Serious Sam",
    "Painkiller",
    "Bulletstorm",
    "Duke Nukem",
    "Shadow Warrior",
    "Warhammer 40K",
    "Warhammer Fantasy",
    "Total Warhammer",
    "Endless Space",
    "Endless Legend",
    "Age of Wonders",
    "Homeworld",
    "StarCraft",
    "Warcraft",
    "Diablo",
    "Path of Exile",
    "Grim Dawn",
    "Torchlight",
    "Titan Quest",
    "Last Epoch",
    "Baldur's Gate",
    "Divinity",
    "Pillars of Eternity",
    "Tyranny",
    "Pathfinder",
    "Kingdoms of Amalur",
    "Wasteland",
    "Fallout Tactics",
    "Gears Tactics",
    "Xenonauts",
    "Darkest Dungeon",
    "Wartales",
    "Battle Brothers",
    "Mordheim",
    "Necromunda",
    "Warhammer 40K Mechanicus",
    "Warhammer 40K Inquisitor",
    "Warhammer 40K Chaos Gate",
    "Phasmophobia",
    "Dead by Daylight",
    "Friday the 13th",
    "Evolve",
    "Left 4 Dead",
    "World War Z",
    "Zombie Army",
    "State of Decay",
    "DayZ",
    "H1Z1",
    "Unturned",
    "SCUM",
    "Conan Exiles",
    "Ark",
    "Atlas",
    "Rust",
    "Miscreated",
    "Surviosis",
    "Hold Your Own",
    "The Cursed Island",
    "Stranded Deep",
    "The Forest",
    "Sons of the Forest",
    "Green Hell",
    "Smalland",
    "Grounded",
    "Raft",
    "Subnautica",
    "Breathedge",
    "Astroneer",
    "No Man's Sky",
    "Elite Dangerous",
    "Star Citizen",
    "Everspace",
    "Everspace 2",
    "Chorus",
    "Evochron",
    "Starsector",
    "Stellaris",
    "Endless Space",
    "Galactic Civilizations",
    "Sins of a Solar Empire",
    "Northgard",
    "They Are Billions",
    "Anno",
    "Tropico",
    "SimCity",
    "Cities Skylines",
    "Transport Fever",
    "Railroad Tycoon",
    "Rollercoaster Tycoon",
    "Planet Coaster",
    "Planet Zoo",
    "Two Point Hospital",
    "Two Point Campus",
    "Prison Architect",
    "RimWorld",
    "Oxygen Not Included",
    "Factorio",
    "Satisfactory",
    "Dyson Sphere Program",
    "Mindustry",
    "Shapez",
    "Captain of Industry",
    "Timberborn",
    "Frostpunk",
    "Surviving Mars",
    "Surviving the Aftermath",
    "Endzone",
    "Cloudpunk",
    "Shadowrun",
    "Deus Ex",
    "System Shock",
    "Observer",
    "VA 11 HALLA",
    "Night Call",
    "Disco Elysium",
    "Citizen Sleeper",
    "Invisible Inc",
    "UFO 50",
    "UFO Enemy Unknown",
    "XCOM",
    "Gears Tactics",
    "Phoenix Point",
    "Battletech",
    "Warhammer 40K Mechanicus",
    "Marvel's Midnight Suns",
    "Gloomhaven",
    "Book of Travels",
    "Griftlands",
    "Cult of the Lamb",
    "Hades",
    "Skul",
    "Curse of the Dead Gods",
    "Returnal",
    "Risk of Rain",
    "Risk of Rain 2",
    "Enter the Gungeon",
    "Binding of Isaac",
    "Spelunky",
    "Dead Cells",
    "Rogue Legacy",
    "Slay the Spire",
    "Monster Train",
    "Inscryption",
    "Stacklands",
    "Dorfromantik",
    "Townscaper",
    "Unrailed",
    "Overcooked",
    "Moving Out",
    "Tools Up",
    "Party Animals",
    "Gang Beasts",
    "Human Fall Flat",
    "Pummel Party",
    "Jackbox",
    "Ultimate Chicken Horse",
    "Boomerang Fu",
    "Bread and Fred",
    "Sniper Elite",
    "Ready or Not",
    "Insurgency",
    "Squad",
    "Arma",
    "DayZ",
    "Miscreated",
    "Life is Feudal",
    "Mortal Online",
    "Albion Online",
    "New World",
    "Black Desert",
    "Elder Scrolls Online",
    "Final Fantasy XIV",
    "Guild Wars",
    "Star Wars The Old Republic",
    "Lost Ark",
    "Throne and Liberty",
    "Tower of Fantasy",
    "Genshin Impact",
    "Honkai Star Rail",
    "Wuthering Waves",
    "Zenless Zone Zero",
    "Palworld",
    "Blue Protocol",
    "Pioneer",
    "Icarus",
    "Once Human",
    "Deliver Us Mars",
    "Deliver Us Moon",
    "We Were Here",
    "Operation Tango",
    "The Dark Pictures",
    "Until Dawn",
    "Outlast",
    "Resident Evil",
    "Silent Hill",
    "Alien Isolation",
    "SOMA",
    "Amnesia",
    "Layers of Fear",
    "Observer",
    "GTA",
    "Saints Row",
    "Watch Dogs",
    "Mafia",
    "Sleeping Dogs",
    "Just Cause",
    "Mad Max",
    "Days Gone",
    "The Last of Us",
    "Uncharted",
    "Tomb Raider",
    "Unravel",
    "Little Nightmares",
    "Inside",
    "Limbo",
    "Braid",
    "Fez",
    "Axiom Ver",
    "Gris",
    "Journey",
    "Sky Children of the Light",
    "Flower",
    "Abzu",
    "Rime",
    "Kena",
    "Sable",
    "Tunic",
    "Aetheris",
    "Outer Wilds",
    "Return of the Obra Dinn",
    "Her Story",
    "Tell Me Why",
    "Life is Strange",
    "The Walking Dead",
    "The Wolf Among Us",
    "Tales from the Borderlands",
    "Batman Telltale",
    "Guardians of the Galaxy Telltale",
    "Minecraft Story Mode",
    "Sam and Max",
    "Poker Night",
    "Stronghold",
    "Age of Empires",
    "Empire Earth",
    "Rise of Nations",
    "0 AD",
    "Northgard",
    "Bad North",
    "Banner Saga",
    "Kingdom",
    "Mini Metro",
    "Mini Motorways",
    "Before We Leave",
    "Aven Colony",
    "Lunar Colony",
    "Offworld Trading Company",
    "Homeworld Deserts of Kharak",
    "Battlezone 99",
    "Iron Harvest",
    "Company of Heroes",
    "Men of War",
    "Call to Arms",
    "Sudden Strike",
    "Blitzkrieg",
    "Codename Panzers",
    "War Front",
    "World in Conflict",
    "Act of War",
    "End of Nations",
    "Grey Goo",
    "Ashes of the Singularity",
    "Planetary Annihilation",
    "Supreme Commander",
    "Natural Selection",
    "Sven Co-op",
    "Synergy",
    "Empires Mod",
    "Zombie Panic",
    "No More Room in Hell",
    "Codename Cure",
    "NMRiH",
    "Insurgency Co-op",
    "Killing Floor",
    "Zombie Panic Source",
    "Left 4 Dead",
    "Zombie Master",
    "Escape Dead Island",
    "Dead Rising",
    "Sunset Overdrive",
    "Bulletstorm",
    "Twisted Metal",
    "Motorstorm",
    "Destruction Derby",
    "Burnout",
    "Need for Speed",
    "The Crew",
    "Forza Horizon",
    "Forza Motorsport",
    "Gran Turismo",
    "Dirt",
    "Colin McRae",
    "WRC",
    "Trackmania",
    "Grip Combat Racing",
    "Redout",
    "Fast RMX",
    "Trials",
    "MX vs ATV",
    "Baja",
    "Snowrunner",
    "Mudrunner",
    "Spintires",
    "BeamNG",
    "Wreckfest",
    "Next Car Game",
    "Flatout",
    "Reckless Racing",
    "Traffic Rider",
    "Asphalt",
    "Real Racing",
    "CSR Racing",
    "Hill Climb Racing",
    "Beach Buggy Racing",
    "Sonic Racing",
    "Crash Team Racing",
    "Spyro",
    "Ratchet and Clank",
    "Jak and Daxter",
    "Sly Cooper",
    "Infamous",
    "God of War",
    "Devil May Cry",
    "Bayonetta",
    "Metal Gear",
    "Metal Gear Rising",
    "Ninja Gaiden",
    "Sekiro",
    "Nioh",
    "Samurai Warriors",
    "Dynasty Warriors",
    "Hyrule Warriors",
    "Fire Emblem Warriors",
    "Dragon Quest Heroes",
    "One Piece Pirate Warriors",
    "Berserk Musou",
    "Attack on Titan",
    "Gundam Versus",
    "Gundam Battle Operation",
    "Mobile Suit Gundam",
    "Titanfall",
    "Mechwarrior",
    "Armored Core",
    "Daemon X Machina",
    "War Thunder",
    "World of Tanks",
    "World of Warships",
    "World of Warplanes",
    "Enlisted",
    "Squad",
    "Hell Let Loose",
    "Post Scriptum",
    "Red Orchestra",
    "Brothers in Arms",
    "Call of Duty",
    "Medal of Honor",
    "Battlefield",
    "Wolfenstein",
    "Enemy Territory",
    "Front Mission",
    "Frontlines",
    "Homefront",
    "Spec Ops",
    "Army of Two",
    "Binary Domain",
    "Vanquish",
    "Anarchy Reigns",
    "Metal Gear Online",
    "Zone of the Enders",
    "Platinum Games",
    "Astral Chain",
    "Wonderful 101",
    "Scalebound",
    "Bleeding Edge",
    "Lawbreakers",
    "Battleborn",
    "Evolve",
    "Dirty Bomb",
    "Paladins",
    "Smite",
    "Heroes of the Storm",
    "Mobile Legends",
    "Arena of Valor",
    "Pokemon Unite",
    "Brawl Stars",
    "Clash Royale",
    "Clash of Clans",
    "Boom Beach",
    "Hay Day",
    "Farmville",
    "Township",
    "City Island",
    "SimCity BuildIt",
    "Fallout Shelter",
    "Last Day on Earth",
    "State of Survival",
    "Last Shelter Survival",
    "Rise of Kingdoms",
    "Lords Mobile",
    "King of Avalon",
    "Game of Thrones Conquest",
    "Clash of Kings",
    "Empire Four Kingdoms",
    "Total War Arena",
    "Legends of Runeterra",
    "Hearthstone",
    "Gwent",
    "Eternal Card Game",
    "Shadowverse",
    "Tetris",
    "Puyo Puyo",
    "Dr Mario",
    "Panel de Pon",
    "Puzzle Quest",
    "Puzzle and Dragons",
    "Chain Chronicle",
    "Granblue Fantasy",
    "Fate Grand Order",
    "Azur Lane",
    "Girls Frontline",
    "Arknights",
    "Blue Archive",
    "Nikke",
    "Goddess of Victory",
    "Tower of God",
    "Seven Deadly Sins",
    "One Punch Man",
    "Dragon Ball Legends",
    "Dragon Ball Z Dokkan",
    "Naruto",
    "Bleach",
    "One Piece Bounty Rush",
    "Fairy Tail",
    "Black Clover",
    "Fire Force",
    "Jujutsu Kaisen",
    "Chainsaw Man",
    "Tokyo Ghoul",
    "Attack on Titan",
    "Sword Art Online",
    "Re Zero",
    "Konosuba",
    "Overlord",
    "That Time I Got Reincarnated",
    "Shield Hero",
    "Goblin Slayer",
    "Log Horizon",
    "Overlord",
    "No Game No Life",
    "Monogatari",
    "Steins Gate",
    "Zero Escape",
    "Danganronpa",
    "Persona",
    "Tokyo Mirage Sessions",
    "Devil Summoner",
    "Shin Megami Tensei",
    "Last Bible",
    "Majin Tensei",
    "Ronduine",
    "Blazing Souls",
    "Accelate",
    "Zill O'll",
    "Digital Devil Saga",
    "Persona Q",
    "Persona 5 Strikers",
    "Catherine",
    "Vanillaware",
    "Odin Sphere",
    "Muramasa",
    "Dragon's Crown",
    "Grimgir",
    "13 Sentinels",
    "Etrian Odyssey",
    "World of Demons",
    "Sol Cresta",
    "Cosmic Star Heroine",
    "Crosscode",
    "Scarlet Nexus",
    "Tales of Arise",
    "Tales of Berseria",
    "Tales of Zestiria",
    "Tales of Xillia",
    "Tales of Graces",
    "Tales of Vesperia",
    "Tales of Symphonia",
    "Tales of Phantasia",
    "Tales of Destiny",
    "Star Ocean",
    "Xenosaga",
    "Baten Kaitos",
    "Grandia",
    "Lunar",
    "SaGa",
    "Romancing SaGa",
    "Live a Live",
    "Chrono Trigger",
    "Chrono Cross",
    "Radical Dreamers",
    "Front Mission",
    "Front Mission Alternative",
    "Front Mission 2087",
    "Front Mission 3",
    "Front Mission Online",
    "Another Century's Episode",
    "Super Robot Wars",
    "SD Gundam",
    "Gundam Battle",
    "Gundam Versus",
    "Gundam Extreme Vs",
    "Gundam Battle Operation",
    "Gundam Battle Universe",
    "Gundam Battle Chronicle",
    "Gundam Battle Assault",
    "Gundam Seed Battle",
    "Gundam Wing Battle",
    "Gundam ZZ Battle",
    "Gundam ZZ",
    "Gundam ZZ Battle Assault",
    "Gundam Seed Destiny",
    "Gundam Seed Battle Assault",
    "Gundam Seed Battle Operation",
    "Gundam Seed Battle Chronicle",
    "Gundam Seed Battle Universe",
    "Gundam Seed Battle Assault 2",
    "Gundam Seed Battle Assault 3",
    "Gundam Seed Battle Assault 4",
    "Gundam Seed Battle Assault 5",
    "Gundam Seed Battle Assault 6",
    "Gundam Seed Battle Assault 7",
    "Gundam Seed Battle Assault 8",
    "Gundam Seed Battle Assault 9",
    "Gundam Seed Battle Assault 10",
]

# --- Генерация игр ---

def generate_games(n=2500):
    games = []
    used_names = set()

    for i in range(n):
        base = random.choice(FRANCHISES)
        # Генерация вариантов названий
        suffixes = [
            "",
            " 2",
            " 3",
            " 4",
            " 5",
            " Remastered",
            " Remake",
            " Ultimate Edition",
            " Definitive Edition",
            " Enhanced Edition",
            " Complete Edition",
            " Anniversary Edition",
            " Special Edition",
            " Collector's Edition",
            " Game of the Year Edition",
            " Legendary Edition",
            " Deluxe Edition",
            " Premium Edition",
            " Standard Edition",
            " Digital Edition",
            " Physical Edition",
            " Limited Edition",
            " First Edition",
            " Last Edition",
            " Final Edition",
            " Alpha Edition",
            " Beta Edition",
            " Omega Edition",
            " Omega Edition 2",
            " Omega Edition 3",
            " Omega Edition 4",
            " Omega Edition 5",
        ]
        name = base + random.choice(suffixes)

        # Уникальность имени
        while name in used_names:
            base = random.choice(FRANCHISES)
            name = base + random.choice(suffixes)
        used_names.add(name)

        platform = random.choice(PLATFORMS_POOL)
        genre = random.choice(GENRES)
        free2play = random.choice(FREE2PLAY_POSSIBILITIES)

        # coop_players и has_pvp
        # ~60% кооп, ~40% без коопа
        is_coop = random.random() < 0.6
        if is_coop:
            coop_pool = ["2", "3", "4", "4", "4", "6", "8", "Many"]
            coop_players = random.choice(coop_pool)
            # PvP тоже может быть
            has_pvp = random.choice(["Yes", "No", "No"])
        else:
            coop_players = ""
            # Может быть PvP или чисто сингл
            has_pvp = random.choice(["Yes", "Yes", "No", "No"])

        year = str(random.randint(2000, 2026))

        # URL (условный, но валидный)
        slug = name.lower().replace(" ", "-").replace("'", "-").replace(":", "-")
        slug = "".join(c for c in slug if c.isalnum() or c in "-_")
        url = f"https://example.com/games/{slug}"

        games.append({
            "name": name,
            "platform": platform,
            "coop_players": coop_players,
            "has_pvp": has_pvp,
            "year": year,
            "genre": ";".join(genre),
            "free2play": free2play,
            "url": url,
        })

    return games


def main():
    print("[*] Generating game_library.csv ...")
    games = generate_games(5000)
    print(f"[*] Generated {len(games)} games")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["name", "platform", "coop_players",
                                               "has_pvp", "year", "genre", "free2play", "url"])
        writer.writeheader()
        writer.writerows(games)

    print(f"[+] Saved to {OUT}")


if __name__ == "__main__":
    main()